### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by bryanpedini** [adyanth/shortpaste#29]
Hello,

I just deployed a test version of this webapp looking for a public (private) URL shortener, and noticed it uses HTTP basic authentication.
It would be nice to implement a login page, perhaps with fail2ban or similar methods against bruteforce attacks.

KR,
Bryan.

**Comment by adyanth** [comment]
See #30

Fail2ban and other such protection (rate limiting, etc) are better added at the reverse proxy. Reimplementing it in every application is not very useful.

See [nginx rate limiting](https://www.nginx.com/blog/rate-limiting-nginx/) and [traefik rate limiting](https://doc.traefik.io/traefik/middlewares/http/ratelimit/).
