### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by bryanpedini** [adyanth/shortpaste#30]
Hello,

It would be nice to implement some sort of 2FA to increase the security of public-facing instances.

KR,
Bryan.

**Comment by adyanth** [comment]
The goal of this was to keep the core as small as possible. The reason for basic auth was to provide a minimal working set. For login with 2FA and others (like I have deployed myself), you can disable the basic auth and put it behind a reverse proxy such as Traefik or nginx. Here is one option for [nginx (not validated)](https://gist.github.com/mjbnz/b402edf819a69e517b0c59710f291da9), but I use this [stack I put together myself](https://github.com/adyanth/portable-oidc). For proper public facing use, the service has to be in front of a reverse proxy.
